--- 
alias: "Pracovna - Google Home přehrává - vypni wakeword "
description: ""
trigger:
  - platform: state
    entity_id:
      - media_player.ghub
    to: playing
condition: []
action:
  - service: switch.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: switch.m5stack_atom_echo_a07ff8_use_wake_word
mode: single
---
alias: "Pracovna - Google Home nepřehrává - zapni wakeword "
description: ""
trigger:
  - platform: state
    entity_id:
      - media_player.ghub
    from: playing
condition: []
action:
  - if:
      - condition: state
        entity_id: switch.m5stack_atom_echo_a07ff8_continuous_assistance
        state: "on"
    then:
      - delay:
          hours: 0
          minutes: 0
          seconds: 2
          milliseconds: 0
      - service: button.press
        metadata: {}
        data: {}
        target:
          entity_id: button.m5stack_atom_echo_a07ff8_ptt
    else:
      - service: switch.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: switch.m5stack_atom_echo_a07ff8_use_wake_word
mode: single
---
alias: "Pracovna - Google Home nepřehrává ani neasistuje - zapni wakeword "
description: ""
trigger:
  - platform: state
    entity_id:
      - binary_sensor.m5stack_atom_echo_a07ff8_asistence_probiha
      - media_player.ghub
    to: "off"
    for:
      hours: 0
      minutes: 0
      seconds: 30
condition:
  - condition: state
    entity_id: binary_sensor.m5stack_atom_echo_a07ff8_asistence_probiha
    state: "off"
    for:
      hours: 0
      minutes: 0
      seconds: 30
  - condition: state
    entity_id: media_player.ghub
    state: "off"
    for:
      hours: 0
      minutes: 0
      seconds: 30
action:
  - service: switch.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: switch.m5stack_atom_echo_a07ff8_use_wake_word
mode: single
